app: url-shortener
service: ${self:app}-resources

frameworkVersion: '4'
useDotenv: true
configValidationMode: error

provider:
  name: aws
  region: eu-west-1
  stage: ${opt:stage, 'dev'}

custom:
  rootDomain: ${cf:${self:app}-dns.RootDomain}
  certificateArn: ${env:CERTIFICATE_ARN}

stages:
  dev:
    params:
      accessTokenValidityInMins: 60
      idTokenValidityInMins: 60
      refreshTokenValidityInMins: 600
  pro:
    params:
      accessTokenValidityInMins: 5
      idTokenValidityInMins: 5
      refreshTokenValidityInMins: 60

resources:
  - Conditions:
      IsPro: !Equals ["${self:provider.stage}", pro]
      IsDev: !Not [Condition: IsPro]

  - ${file(resources/web.resources.yml)}
  - ${file(resources/db.resources.yml)}
  - ${file(resources/users.resources.yml)}
  - ${file(resources/dns.resources.yml)}

  - Outputs:
      UserPoolArn:
        Value: !GetAtt CognitoUserPool.Arn
      UserPoolId:
        Value: !Ref CognitoUserPool
      UserPoolClientId:
        Value: !Ref CognitoUserPoolClient
      UserPoolDomain:
        Value: !If [IsPro, !Ref CognitoUserPoolDomain, !Ref CognitoUserPoolDomainPrefix]
      RedirectBucketName:
        Value: !Ref RedirectBucket
      LinksTable:
        Value: !Ref LinksTable
      UsersTable:
        Value: !Ref UsersTable
      UniquesTable:
        Value: !Ref UniquesTable
      CountersTable:
        Value: !Ref CountersTable
