Resources:
  WebsiteDNSName:
    Type: AWS::Route53::RecordSetGroup
    Condition: IsPro
    Properties:
      HostedZoneName: ${self:custom.rootDomain}.
      RecordSets:
        - Name: ${self:custom.rootDomain}
          Type: A
          AliasTarget:
            # https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName:
              Fn::GetAtt: [ CloudFrontDistribution, DomainName ]
            EvaluateTargetHealth: false
  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Condition: IsPro
    DependsOn: RootDomainDNSRecord
    Properties:
      CustomDomainConfig:
        CertificateArn: ${self:custom.certificateArn}
      Domain: auth.${self:custom.rootDomain}
      UserPoolId:
        Ref: CognitoUserPool
  CognitoUserPoolDomainPrefix:
    Type: AWS::Cognito::UserPoolDomain
    Condition: IsDev
    Properties:
      Domain:
        Fn::Join:
          - '-'
          - Fn::Split: [ '.', 'auth.dev.${self:custom.rootDomain}' ]
      UserPoolId:
