Resources:
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [IsPro, "${self:custom.rootDomain}", "dev.${self:custom.rootDomain}"]
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      WebsiteConfiguration:
        IndexDocument: index.html
  WebBucket:
    Type: AWS::S3::Bucket
    Condition: IsPro
    Properties:
      BucketName: "${self:custom.rootDomain}-web"
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      WebsiteConfiguration:
        IndexDocument: index.html
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: IsPro
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: RedirectBucketOrigin
            DomainName: !Select [1, !Split ["://", !GetAtt RedirectBucket.WebsiteURL]]
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
          - Id: WebBucketOrigin
            DomainName: !Select [1, !Split ["://", !GetAtt WebBucket.WebsiteURL]]
            OriginPath: /dist
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        CustomErrorResponses:
          - ErrorCode: '404'
            ResponsePagePath: "/404.html"
            ResponseCode: '200'
            ErrorCachingMinTTL: '30'
        Aliases:
          - ${self:custom.rootDomain}
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: ${self:custom.certificateArn}
          SslSupportMethod: sni-only
          MinimumProtocolVersion: 'TLSv1.2_2021'
        HttpVersion: 'http2'
        CacheBehaviors:
          - PathPattern: '*.html'
            TargetOriginId: WebBucketOrigin
            CachePolicyId: b2884449-e4de-46a7-ac36-70bc7f1ddd6d
            ViewerProtocolPolicy: 'redirect-to-https'
            # Caching Optimized for uncompressed objects (AWS managed cache policy)
            # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html
          - PathPattern: '*.css'
            TargetOriginId: WebBucketOrigin
            # Caching Optimized (AWS managed cache policy)
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            Compress: true
            ViewerProtocolPolicy: 'redirect-to-https'
          - PathPattern: '*.js'
            TargetOriginId: WebBucketOrigin
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            Compress: true
            ViewerProtocolPolicy: 'redirect-to-https'
          - PathPattern: '*.js.map'
            TargetOriginId: WebBucketOrigin
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ViewerProtocolPolicy: 'redirect-to-https'
          - PathPattern: '*.css.map'
            TargetOriginId: WebBucketOrigin
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ViewerProtocolPolicy: 'redirect-to-https'
        DefaultCacheBehavior:
          TargetOriginId: RedirectBucketOrigin
          # Caching disabled (AWS managed cache policy)
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          ViewerProtocolPolicy: 'redirect-to-https'
