name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: 🧪 Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: just test

      - name: ⬆️ Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: testResults/
